# Database location settings (Required)
database_in=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new

# Define what to check
/etc p+i+n+u+g+s+m+c+sha256
/bin R
/sbin R
/usr/bin R
/usr/sbin R
/lib R
/usr/lib R

# Exclude things that change frequently
!/var/log/.*$
!/var/cache/.*$
!/tmp/.*$
!/var/tmp/.*$
